namespace PetFamily.Application.VolunteersFeatures.DTOs;

public record PetData(
    Guid PetId,
    Guid VolunteerId,
    Guid SpeciesId,
    Guid BreedId,
    string Name,
    string Description,
    string Color,
    string HealthInformation,
    string City,
    string Street,
    string House,
    double Weight,
    double Height,
    string PhoneNumber,
    bool IsNeutered,
    DateOnly DateOfBirth,
    bool IsVaccinated,
    string HelpStatus,
    IEnumerable<RequisitesDto> Requisites,
    string? MainFile);

public record PetDto(
    Guid PetId,
    Guid VolunteerId,
    string SpeciesName,
    string BreedName,
    string Name,
    string Description,
    string Color,
    string HealthInformation,
    string City,
    string Street,
    string House,
    double Weight,
    double Height,
    string PhoneNumber,
    bool IsNeutered,
    DateOnly DateOfBirth,
    bool IsVaccinated,
    string HelpStatus,
    IEnumerable<RequisitesDto> Requisites,
    string MainFileDownloadLink);